### ISSUE TITLE
Readme not to date

### ISSUE THREAD

**Issue by NicolasDemangeat** [verschuur/laravel-robotstxt#17]
Hi

In the Readme the command : `php artisan vendor:publish --provider="Verschuur\Laravel\RobotsTxt\RobotsTxtProvider"`  is not good 

replace by : `php artisan vendor:publish --provider="Verschuur\Laravel\RobotsTxt\Providers\RobotsTxtProvider"`

Thanks

**Comment by verschuur** [comment]
No idea how that went unnoticed for so long 🤔. Anyway it's been updated, thanks @IT-Joris for the update!
