### ISSUE TITLE
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN) Class 'App\Http\Controllers\Controller' not found

### ISSUE THREAD

**Issue by nclifton** [verschuur/laravel-robotstxt#2]
Hi,
If you've changed the namespace of your app then you'll have a problem using this package.
The parent controller for us is not under the App namespace.

**Comment by verschuur** [comment]
Thanks for bringing this to my attention. I have to admit that I never change the app namespace, so I didn't take this into account. I'll fix this asap.

**Comment by Quezler** [comment]
@nclifton not sure if you still need this package, but i stumbled upon it and made a pull request for this issue, #3 😸

**Comment by verschuur** [comment]
Thanks for the pull request @Quezler! I merged the request into master and tagged a new release, v1.1.1
