### ISSUE TITLE
How can I add a sitemap?

### ISSUE THREAD

**Issue by Max1mCom** [verschuur/laravel-robotstxt#4]
Hi,

How can I add a directive for sitemap?
Like:
http://mysite.net/sitemap.xml?

**Comment by verschuur** [comment]
Hi,

What exactly is your intention? Do you mean to whitelist a file in the robots.txt?

**Comment by Max1mCom** [comment]
Hi,

This is a special directive in the end of robots.txt:

`Sitemap: https://domain.com/sitemap.xml`

**Comment by verschuur** [comment]
Ah I see. I did not know about that directive, thanks for informing me! 👍At this moment, it is not possible to add that directive. I am about to start on a v2, so I'll be sure to have a look at that directive.

**Comment by Max1mCom** [comment]
Ok, I see. Thanks.

**Comment by vlados** [comment]
When we can expect something because sitemap directive is very important

**Comment by yudi-glive** [comment]
This repo is very useful, but i need the sitemap directive too. Any news on this?

**Comment by vlados** [comment]
I am seeing that there is a brach dev-2.0 where this is directive is adopted

**Comment by verschuur** [comment]
My apologies for not giving any updates. I started working on a 2.0 version that has the sitemap directive (among other things), but life got in the way and I didn't have time to continue developing that version. I'm planning to pick it up soon, but I can't give any specific dates, sorry about that.

**Comment by vlados** [comment]
How we can help?

**Comment by verschuur** [comment]
Well I have a bunch of features I want to add, but I think that the easiest right now would to only add the sitemap directives a.s.a.p, and leave the rest for future features.

**Comment by verschuur** [comment]
I did some work and added the sitemap directives in the dev-2.0 branch. I still need to do some more testing before I'm confident it's production-ready. The structure of the paths in the config has been overhauled, so I need to write an upgrade guide and update the readme.

Hopefully, I can release a production-ready v2.0 somewhere in the next week.

**Comment by vlados** [comment]
Thats great! Bravo!

**Comment by verschuur** [comment]
[Here is v2.0 😁](https://github.com/verschuur/laravel-robotstxt/releases/tag/v2.0.0). Please see the [upgrade guide](https://github.com/verschuur/laravel-robotstxt/blob/master/UPGRADE.md) for the required changes. If you have any question or bug reports, please open a new issue. 

And apologies for the long delays.
